// <auto-generated />
using GraphApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphDbApi.Migrations
{
    [DbContext(typeof(GraphApiContext))]
    [Migration("20220921140025_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GraphApi.Models.Edge", b =>
                {
                    b.Property<int>("EdgeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EdgeID"), 1L, 1);

                    b.Property<int>("DestID")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<int>("SrcID")
                        .HasColumnType("int");

                    b.HasKey("EdgeID");

                    b.HasIndex("DestID");

                    b.HasIndex("SrcID");

                    b.ToTable("Edges");
                });

            modelBuilder.Entity("GraphApi.Models.Node", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("GraphApi.Models.Edge", b =>
                {
                    b.HasOne("GraphApi.Models.Node", "Dest")
                        .WithMany("DestEdges")
                        .HasForeignKey("DestID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GraphApi.Models.Node", "Src")
                        .WithMany("SrcEdges")
                        .HasForeignKey("SrcID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Dest");

                    b.Navigation("Src");
                });

            modelBuilder.Entity("GraphApi.Models.Node", b =>
                {
                    b.Navigation("DestEdges");

                    b.Navigation("SrcEdges");
                });
#pragma warning restore 612, 618
        }
    }
}
